name: Manish Kumar Singh
description: Blog
meta_description: "Tech Blog"

markdown: kramdown
logo: false
paginate: 10
baseurl: /
domain_name: 'http://coolmanishks.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://coolmanishks.github.io'
author:      'Manish Kumar Singh'
